### ISSUE TITLE
How to change Input1Ref

### ISSUE THREAD

**Issue by finnnm** [adl1995/generalised-hough-transform#5]
When i change the Inout1Ref Image it says: 

Traceback (most recent call last):
  File "generalized_hough_demo.py", line 19, in <module>
    table = buildRefTable(refim)
  File "C:\Users\Bachelorarbeit\generalised-hough-transform\build_reference_table.py", line 35, in buildRefTable
    if (img[x, y] != 0):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Can you help?

**Comment by TWTom041** [comment]
try performing canny on the image first
